import { createGlobalStyle } from "styled-components";

const GlobalStyle = createGlobalStyle(({ theme }) => ({
  ":root": {
    "--base-spacing-auto": "auto",
    "--base-spacing-0": 0,
    "--base-spacing-1": 1,
    "--base-spacing-x3s": "0.125rem",
    "--base-spacing-x2s": "0.25rem",
    "--base-spacing-xs": "0.5rem",
    "--base-spacing-sm": "0.75rem",
    "--base-spacing-md": "1rem",
    "--base-spacing-lg": "1.25rem",
    "--base-spacing-xl": "1.5rem",
    "--base-spacing-x2l": "2rem",
    "--base-spacing-x3l": "2.5rem",
    "--base-spacing-x4l": "2.75rem",
    "--base-spacing-x5l": "3rem",
    "--base-spacing-x6l": "3.5rem",
    "--base-spacing-x7l": "4rem",
    "--base-spacing-x8l": "6rem",
    "--base-font-sans": [
      "futura-pt",
      "system-ui",
      "-apple-system",
      "'Segoe UI'",
      "Roboto",
      "Ubuntu",
      "Cantarell",
      "Noto Sans",
      "sans-serif",
      "BlinkMacSystemFont",
      "Helvetica",
      "Arial",
      "sans-serif",
      "'Apple Color Emoji'",
      "'Segoe UI Emoji'",
      "'Segoe UI Symbol'",
    ].join(" "),
    "--base-font-serif": [
      "freight-display-pro",
      "Cambria",
      "'Hoefler Text'",
      "Utopia",
      "'Liberation Serif'",
      "'Nimbus Roman No9 L Regular'",
      "Times",
      "'Times New Roman'",
      "serif",
    ].join(" "),
    "--base-color-pink-200": "255 245 255",
    "--base-color-pink-300": "255 224 255",
    "--base-color-pink-400": "255 204 255",
    "--base-color-pink-500": "255 153 255",
    "--base-color-pink-600": "204 102 204",
    "--base-color-pink-700": "68 34 68",
    "--base-color-pink-800": "26 15 26",
    "--base-color-gray-100": "255 255 255",
    "--base-color-gray-900": "51 51 51",
    "--base-color-red-500": "255 51 51",
    "--base-color-red-600": "204 0 0",
    "--base-color-blue-500": "51 153 255",
    "--base-color-blue-600": "0 102 187",
    "--base-color-yellow-500": "255 238 170",
    "--base-color-yellow-600": "204 204 119",
    "--base-color-alpha-enabled": 1,
    "--base-color-alpha-hovered": 0.6,
    "--base-color-alpha-disabled": 0.4,
  },
  html: {
    "--palette-primary": "--base-color-pink-500",
    "--palette-secondary": "--base-color-pink-400",
    "--palette-surface": "--base-color-pink-300",
    "--palette-background": "--base-color-pink-200",
    "--palette-text": "--base-color-gray-100",
    "--palette-error": "--base-color-red-600",
    "--palette-warning": "--base-color-yellow-600",
    "--palette-success": "--base-color-blue-600",
    [theme.media.dark]: {
      "--palette-secondary": "--base-color-pink-600",
      "--palette-surface": "--base-color-pink-700",
      "--palette-background": "--base-color-pink-800",
      "--palette-text": "--base-color-gray-900",
      "--palette-error": "--base-color-red-500",
      "--palette-warning": "--base-color-yellow-500",
      "--palette-success": "--base-color-blue-500",
    },
    // TODO: Set <h2, h3, h4, p, span> and <padding, margin> values
  },
  body: {
    margin: 0,
    textRendering: "optimizeLegibility",
    textSizeAdjust: "100%",
    lineHeight: "1.5em",
    fontSize: theme.typography.md,
    fontFamily: theme.font.sans,
    backgroundColor: theme.palette.main.xlight,
    color: theme.palette.dark,
    "-webkit-font-smoothing": "auto",
    "-moz-osx-font-smoothing": "auto",
    [theme.media.dark]: {
      colorScheme: "dark",
      backgroundColor: theme.palette.main.xdark,
      color: theme.palette.light,
      "-webkit-font-smoothing": "antialiased",
      "-moz-osx-font-smoothing": "grayscale",
    },
  },
}));

export default GlobalStyle;
