export default {
  color: {
    primary: "var(--color-primary)",
    secondary: "var(--color-secondary)",
    tertiary: "var(--color-tertiary)",
    background: "var(--color-background)",
    foreground: "var(--color-foreground)",
    error: "var(--color-error)",
    warning: "var(--color-warning)",
    success: "var(--color-success)",
  },
  action: {
    focus: "var(--action-focus)",
    default: "var(--action-default)",
    hover: "var(--action-hover)",
    disable: "var(--action-disable)",
  },
  text: {
    sans: "var(--type-sans)",
    serif: "var(--type-serif)",
    overline: "var(--text-overline)",
    body: "var(--text-body)",
    subtitle: "var(--text-subtitle)",
    subhead: "var(--text-subhead)",
    headline: "var(--text-headline)",
  },
  media: {
    md: "@media screen and (min-width: 40rem)",
    lg: "@media screen and (min-width: 80rem)",
    dark: "@media (prefers-color-scheme: dark)",
    motion: "@media (prefers-reduced-motion: no-preference)",
  },
  size: {
    2: "var(--size-02)",
    4: "var(--size-04)",
    8: "var(--size-08)",
    12: "var(--size-12)",
    16: "var(--size-16)",
    24: "var(--size-24)",
    32: "var(--size-32)",
    48: "var(--size-48)",
    96: "var(--size-96)",
  },
  grid: {
    padding: "var(--grid-padding)",
    margin: "var(--grid-margin)",
  },
} as const;
