export const theme = {
  channel: {
    background: "var(--channel-background)",
    foreground: "var(--channel-foreground)",
    main: "var(--channel-main)",
    accent: "var(--channel-accent)",
    success: "var(--channel-success)",
    error: "var(--channel-error)",
    warning: "var(--channel-warning)",
  },
  alpha: {
    primary: "var(--alpha-primary)",
    backdrop: "var(--alpha-backdrop)",
    secondary: "var(--alpha-secondary)",
    tertiary: "var(--alpha-tertiary)",
    shadow: "var(--alpha-shadow)",
    opaque: "var(--alpha-opaque)",
  },
  sizing: {
    sm: "var(--sizing-sm)",
    md: "var(--sizing-md)",
    lg: "var(--sizing-lg)",
    xl: "var(--sizing-xl)",
    x2l: "var(--sizing-x2l)",
    x3l: "var(--sizing-x3l)",
    x4l: "var(--sizing-x4l)",
    x5l: "var(--sizing-x5l)",
    x6l: "var(--sizing-x6l)",
  },
  grid: {
    padding: "var(--grid-padding)",
    margin: "var(--grid-margin)",
    area: "var(--grid-area)",
  },
  kerning: {
    tight: "var(--kerning-tight)",
    wide: "var(--kerning-wide)",
  },
  weight: {
    regular: "var(--weight-regular)",
    bold: "var(--weight-bold)",
    bolder: "var(--weight-bolder)",
    heavy: "var(--weight-heavy)",
  },
  media: {
    DEFAULT: "",
    md: "@media (min-width: 512px)",
    lg: "@media (min-width: 1024px)",
    dark: "@media (prefers-color-scheme: dark)",
    motion: "@media (prefers-reduced-motion: no-preference)",
  },
} as const;
