import Assets from "public";

export default function getExhibition(
  exhibition = {
    title: [
      "Década de 1960",
      "Década de 1970",
      "Década de 1980",
      "Década de 1990",
      "Década de 2000",
      "Década de 2010",
    ],
    dean: {
      alt: [
        ["Aristóteles Calazans Simões"],
        ["Nabuco Lopes", "Manoel Ramalho"],
        ["João Azevedo", "Fernando Gama", "Delza Gitaí"],
        ["Fernando Gama", "Rogério Pinheiro"],
        ["Ana Dayse Dorea"],
        ["Eurico Lôbo", "Valéria Correia", "Josealdo Tonholo"],
      ],
      src: [
        [Assets.pr1960s01],
        [Assets.pr1970s01, Assets.pr1970s02],
        [Assets.pr1980s01, Assets.pr1980s02, Assets.pr1980s03],
        [Assets.pr1990s01, Assets.pr1990s02],
        [Assets.pr2000s01],
        [Assets.pr2010s01, Assets.pr2010s02, Assets.pr2010s03],
      ],
      year: [
        ["1961 • 1971"],
        ["1971 • 1975", "1975 • 1979"],
        ["1979 • 1983", "1983 • 1987", "1987 • 1991"],
        ["1991 • 1995", "1995 • 2003"],
        ["2003 • 2011"],
        ["2011 • 2015", "2016 • 2020", "2020 • atualmente"],
      ],
      description: [
        [
          "No final do governo de Juscelino Kubitschek, no Palácio da Alvorada, na capital da república recém-transferida para Brasília, o reitor Aristótoles Calazans Simões alcançou a assinatura presidencial para a criação da Universidade Federal de Alagoas. Sobre esse período, disse o reitor: /quote Num Estado pequeno e pobre como as Alagoas, a instituição e o desenvolvimento de uma Universidade em seu seio trará, não tenhamos dúvida, verdadeira revolução não somente sociocultural mas, ainda, verdadeira revolução econômico-financeira.",
        ],
        [
          "Na gestão do reitor Nabuco Lopes, a Ufal investiu na expansão e qualificação do quadro de servidores docentes e técnico-administrativos. O reitor buscou financiamento para cursos de aperfeiçoamento, especialização, e, inclusive, as primeiras bolsas de mestrado e doutorado. Em seu discurso, na comemoração dos 25 anos da Ufal, Nabuco Lopes relembrou esse esforço: /quote O programa ensaiou seus primeiros passos favorecendo professores e alunos com estágios de aperfeiçoamento, monitoria e iniciação científica. Na realidade, a maior beneficiária era a própria instituição na medida em que, dessa forma, se contribuía para enriquecer a qualidade das atividades universitárias.",
          "Na gestão do engenheiro Manoel Ramalho como reitor da Ufal, alguns cursos ainda funcionavam no Campus Tamandaré, no Pontal, quando foi implantada a empresa Salgema naquela região. O jornalista e economista Roberto Vilanova, que era estudante nesse período, relatou em seu blog que o reitor, mesmo em tempos de Ditadura Militar, agiu com firmeza e coragem: /quote O reitor Manoel Ramalho exigiu uma brigada de combate a incêndio do Corpo de Bombeiros e 500 máscaras contra gás, numa permanente atitude de vigilância, para continuar com a área 3 da Ufal no Pontal da Barra./ Como a exigência não foi atendida, os cursos foram transferidos para o Campus A.C. Simões.",
        ],
        [
          "O reitor João Azevedo foi empossado no cargo no período em que se intensificaram as lutas sociais pela abertura política no Brasil. A solenidade de posse foi representativa dessa época histórica, segundo narra o historiador Edberto Ticianeli: /quote Como a posse do novo reitor, João Azevedo, aconteceria no dia 29 de novembro de 1979, os alunos da Ufal preparam uma ação para impedir o ato, caso não houvesse proposta da Reitoria para as suas reivindicações. Na quinta-feira (29) à tarde, a Reitoria, que ficava na Praça Sinimbu, foi tomada de assalto por centenas de estudantes. O auditório, onde haveria a transmissão de cargo, foi invadido e ocupado por jovens com faixas que cobravam o direito do representante da UNE falar na solenidade. Houve uma negociação e ficou acertado que Aldo Rebelo, então secretário-geral da entidade nacional dos estudantes, usaria da palavra.",
          "O primeiro mandato do professor Fernando Gama, ainda por indicação do presidente João Figueiredo, foi marcado pela expansão da Ufal. O reitor buscou recursos para duplicar a estrutura física da Universidade, no Campus A.C. Simões. na Cidade Universitária. No livro dos 50 anos da Ufal, ressalta-se que Gama foi um grande defensor da comunidade universitária, aberto ao diálogo com as entidades estudantis e sindicais. 'Para as entidades que congregavam docentes e servidores, o reitor Gama sempre teve a mão estendida, colaborando, inclusive, nas políticas assistenciais e nas condições de funcionamento dos órgãos corporativos.'",
          "A gestão da professora Delza Gitaí marca a democratização da Universidade, condizente com os tempos de redemocratização do país. O Congresso Acadêmico realizando ainda na gestão do professor Gama aprovou a eleição direta para o cargo de reitor. Delza Gitaí foi a primeira gestão eleita pelo voto da comunidade universitária. Também foi a primeira mulher a ocupar o cargo na Reitoria da Ufal. Na sua gestão, foi inaugurada a nova Reitoria na Cidade Universitária. Na antiga Reitoria, por pressão dos estudantes, que se organizaram e ocuparam parte da sede na praça Sinimbú, foi reaberta a Residência Universitária. Também foi marcante a atuação da Reitora no enfrentamento ao analfabetismo, estabelecendo parcerias com instituições em Alagoas e realizando o 1º Seminário Estadual sobre Alfabetização e Cidadania, com a participação de Paulo Freire.",
        ],
        [
          "Dessa vez, eleito pelo voto direto, o professor Fernando Gama retorna para mais uma gestão como reitor da Ufal. Nessa etapa, enfrentando várias dificuldades, o reitor conseguiu atender a uma demanda por cursos noturnos, para o acesso à Universidade de trabalhadores e trabalhadoras, além de revitalizar a Fazenda São Luiz, em Viçosa, como campo de pesquisa agropecuária. Foi um período também de fortes reivindicações das entidades sindicais representativas dos docentes e técnico-administrativos das universidades brasileiras, que sofreram muitas perdas salariais no período do governo de FHC.",
          "O primeiro mandato do reitor Rogério Pinheiro destacou-se pelo planejamento administrativo para adequar as ações da Universidade às condições do orçamento. Registra-se ainda a tramitação para que posteriormente fossem abertos novos mestrados, como o Prodema -mestrado em Desenvolvimento e Meio Ambiente. As ações de extensão também foram fortalecidas, com a criação do Núcleo Temático de Assistência Social (Nutas), Núcleo de Educação Ambiental (NEA) e Núcleo de Educação a Distância (Nead), além da revitalização da Editora Universitária (Edufal), com a realização da 1ª Bienal do Livro e da Arte, em 1998. No segundo mandato foi inaugurado o Radar Meteorológico da Ufal.",
        ],
        [
          "A reitora Ana Dayse Dorea também foi eleita por dois mandatos consecutivos. Neste período, a reitora soube aproveitar ao máximo a política do Governo Lula para a expansão do Ensino Superior. Com recursos federais, a Ufal inaugurou o Campus Arapiraca, em setembro de 2006. Em seguida, a Universidade aderiu ao Programa de Apoio a Planos de Reestruturação e Expansão das Universidades Federais (Reuni). Com o financiamento do programa, foi possível inaugurar o Campus do Sertão, já no segundo mandato, em 2010. Nessa ocasião muito comemorada, a reitora Ana Dayse disse: /quote A universidade brota da pedra e da caatinga. Essa história será contada por vocês, e estejam certos que estamos ajudando a fazer um Brasil diferente, a acabar com indicadores sociais que ainda envergonham o nosso Estado.",
        ],
        [
          "Em dezembro de 2011, foi empossado o reitor Eurico Lôbo. O desafio dessa gestão foi consolidar a expansão, qualificando os campi do interior, e responder também a uma educação globalizada, com muitas ações de intercâmbio internacional. A Assessoria Internacional da Ufal trabalhou a todo vapor. A Universidade chegou a ter 200 estudantes no exterior no mesmo período. Só pelo programa Ciências sem Fronteiras, em 2012, enquanto cerca de 70 alunos estavam retornando dos intercâmbios realizados no primeiro semestre, aproximadamente 60 estavam arrumando as malas e organizando a documentação para embarcar. Além da internacionalização, a modernização dos sistemas de comunicação, com a implantação da rede lógica, possibilitou uma Universidade em diálogo com o mundo. Nessa gestão e embaixo de muita polêmica, o Hospital Universitário (HU) aderiu à Rede Ebserh -Empresa Brasileira de Serviços Hospitalares, empresa pública de direito privado do Governo Federal.",
          "A gestão da professora Valéria Correia é marcada pela proposta de Universidade socialmente referenciada. A Ufal implantou o Fórum Social Universitário e fortaleceu as parcerias com as entidades da sociedade civil organizada. No seu mandato, Valéria Correia inaugurou o primeiro curso de bacharelado em Agroecologia, promovido pelo Programa Nacional de Educação na Reforma Agrária (Pronera) em parceria com o Centro de Ciências Agrárias (Ceca), para a formação superior de assentados. Sobre a universidade, Valéria Correia afirmou: /quote Somos uma organização histórica, com a responsabilidade de responder às demandas da sociedade do presente. Isso nos leva a pensar o contexto político, social, cultural e econômico do nosso tempo. Contexto em que a defesa da universidade pública deve ser reafirmada.",
          "Essa década é iniciada com a posse do Reitor Josealdo Tonholo, para um mandato que prossegue até 2024. Ao tomar posse, em 28 de janeiro de 2020, o reitor afirmou o papel social, econômico e educacional da Universidade. /quote A melhor maneira de legitimar tudo isso é aproximá-la dos mais diferentes segmentos e setores da sociedade civil local: na sua dimensão produtivo-econômica, na sua dimensão político-partidária e na dimensão dos movimentos sociais. Nosso desafio é gigantesco, mas é também extremamente estimulante/ disse Tonholo.",
        ],
      ],
    },
    gallery: {
      alt: [
        [
          "Canteiro de obras",
          "Construção do Instituto de Química - outubro de 1968",
          "Presidente Juscelino Kubitschek sancionando a lei de criação da Ufal - janeiro de 1961",
          "Sala de Aula do Curso de Administração e Economia - junho de 1969",
          "Trabalhadores no canteiro de obras da Ufal",
          "Tomada do campus da Ufal em construção",
          "Reunião do Conselho Universitário da Ufal quando da assinatura do contrato para elaboração do Plano Diretor da construção da Cidade Universitária - 1965",
          "Residência Universitária Masculina - 1966",
          "Prédio que se tornaria sede da 1° Reitoria da Ufal na Praça Sinimbu",
          "Início das obras de implantação do Campus, na Cidade Universitária - 1967",
        ],
        [
          "Capa da primeira edição da Revista Scientia Ad Sapientiam lançada em 1978",
          "Diploma recebido pelo Corufal pela participação do 3º Festival Nacional de Coros em outubro de 1971",
          "Formatura Unificada no Estádio Rei Pelé - 1974",
          "Impresso contendo a programação da 1ª Semana de Cultura Popular - 1976",
          "Inauguração do Núcleo de Educação Física e Desportos - abril de 1974",
          "Inauguração do Salão Nobre Professor Guedes de Miranda - 1975",
          "Instalação do Museu de Artes plásticas - 1975",
          "Ministro Ney Braga, Governador Divaldo Suruagy e Reitor Nabuco Lopes ",
          "Navio Hope em Maceió - março de 1977",
          "Vista parcial do Vestibular Unificado, realizado no Estádio Rei Pelé - 1973",
        ],
        [
          "Visita do Ministro da Educação Jorge BornHausen às dependências da Ufal - março de 1986",
          "Abertura dos Jogos Internos do Curso de Educação Física - setembro de 1988",
          "Campanha para Reitor da Ufal - 1986",
          "Cônsul da Alemanha em visita à Ufal - outubro de 1989",
          "Embaixador de Israel em visita a Ufal",
          "Ex-reitores na comemoração de 25 anos da Ufal - janeiro de 1986",
          "Manifestação dos Estudantes da Ufal reinvidicando o Restaurante Universitário - março de 1988",
          "Inauguração da reitoria no campus universitário - novembro de 1987",
          "Espaço Cultural da Ufal - dezembro de 1989",
          "Eleição direta para reitor. Flagrante da apuração de votos - novembro de 1986",
        ],
        [
          "Atendimento aos alunos na Proest - 1994",
          "Aula Inaugural do Curso de Formação do Ator no Circo Cultural - dezembro de 1990",
          "Aula Inaugural Noturna março 96",
          "Frei Beto em sessão de autógrafos na Bienal do Livro set 98",
          "Inauguração das salas de música do Departamento de Arte março 91",
          "Novos alunos passando pela experiência do trote - janeiro de 1997",
          "Primeira defesa de tese do curso de mestrado em Letras da Ufal - maio de 1991",
          "Assinatura de convência com o MEC sobre o programa nacional de Alfabetização - novembro de 1990",
          "Reitor Rogério Pinheiro, a diretora do Museu Théo Brandão, Cármen Lúcia Dantas, e o senador Teotônio Vilela Filho, que destinou recursos de emenda parlamentar para restauração do MTB -1999",
          "Exposição de livros no pátio da Reitoria promovida pela Edufal - agosto de 1996",
        ],
        [
          "Reunião do Consuni sobre cotas raciais - novembro de 2003",
          "Inauguração Fórum Ufal-CJUR - fevereiro 2001",
          "XI Encontro Nacional de Corais Amadores - setembro de 2004",
          "Abertura da exposição de paineis em comemoração aos 45 anos da Ufal no Shopping Iguatemi  - janeiro de 2006",
          "Abertura dos Jogos Internos - novembro de 2008",
          "Alunos da rede púplica de ensino participando da Expofísica - maio de 2006 ",
          "Área destinada à construção da sede da Ufal em Delmiro Gouveia - 2010",
          "Inauguração do busto do primeiro reitor, AC Simoes - janeiro de 2001",
          "Público na II Bienal Internacional do Livro - outubro de 2005",
          "Reinauguração do Museu Théo Brandão, em julho de 2002. Avenida da Paz fechada para a celebração.",
        ],
        [
          "Solenidade de Abertura do Caiite 2016",
          "Tenda Cultural da Ufal",
          "Apresentação teatral parte do Natal da Avenida, realizado no Museu Theo Branão",
          "Criança recebendo atendimento na Faculdade de Odontologia ",
          "Integrantes do Movimento dos Trabalhadores sem Terra fazem plantio em terreno ocioso da Ufal",
          "Montagem das estruturas da SBPC no campus A.C. Simões",
          "Público tomando as ruas do Jaraguá na 9ª edição da Bienal Internacional do Livro de Alagoas",
          "Sede do Campus do Sertão em Delmiro Gouveia",
          "Apresentação Musical durante as atividades do Caiite em Penedo",
        ],
      ],
      src: [
        [
          Assets.de1960s01,
          Assets.de1960s02,
          Assets.de1960s03,
          Assets.de1960s04,
          Assets.de1960s05,
          Assets.de1960s06,
          Assets.de1960s07,
          Assets.de1960s08,
          Assets.de1960s09,
          Assets.de1960s10,
        ],
        [
          Assets.de1970s01,
          Assets.de1970s02,
          Assets.de1970s03,
          Assets.de1970s04,
          Assets.de1970s05,
          Assets.de1970s06,
          Assets.de1970s07,
          Assets.de1970s08,
          Assets.de1970s09,
          Assets.de1970s10,
        ],
        [
          Assets.de1980s01,
          Assets.de1980s02,
          Assets.de1980s03,
          Assets.de1980s04,
          Assets.de1980s05,
          Assets.de1980s06,
          Assets.de1980s07,
          Assets.de1980s08,
          Assets.de1980s09,
          Assets.de1980s10,
        ],
        [
          Assets.de1990s01,
          Assets.de1990s02,
          Assets.de1990s03,
          Assets.de1990s04,
          Assets.de1990s05,
          Assets.de1990s06,
          Assets.de1990s07,
          Assets.de1990s08,
          Assets.de1990s09,
          Assets.de1990s10,
        ],
        [
          Assets.de2000s01,
          Assets.de2000s02,
          Assets.de2000s03,
          Assets.de2000s04,
          Assets.de2000s05,
          Assets.de2000s06,
          Assets.de2000s07,
          Assets.de2000s08,
          Assets.de2000s09,
          Assets.de2000s10,
        ],
        [
          Assets.de2010s01,
          Assets.de2010s02,
          Assets.de2010s03,
          Assets.de2010s04,
          Assets.de2010s05,
          Assets.de2010s06,
          Assets.de2010s07,
          Assets.de2010s08,
          Assets.de2010s09,
        ],
      ],
    },
  },
) {
  return exhibition.title.map((title: string, index: number) => ({
    title,
    dean: exhibition.dean.alt[index].map((alt: string, deanIndex: number) => ({
      alt,
      src: exhibition.dean.src[index][deanIndex],
      year: exhibition.dean.year[index][deanIndex],
      description: exhibition.dean.description[index][deanIndex],
    })),
    gallery: exhibition.gallery.alt[index].map(
      (alt: string, galleryIndex: number) => ({
        alt,
        src: exhibition.gallery.src[index][galleryIndex],
      }),
    ),
  }));
}
